#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset

SCRIPTS="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
readonly SCRIPTS

source "${SCRIPTS}/lib_logging.sh"

: "${DEVKIT_HOST_PROJECT_ROOT:="$("${SCRIPTS}"/find_project_root)"}"
: "${DEVKIT_CONTAINER_PROJECT_ROOT:="${DEVKIT_HOST_PROJECT_ROOT}"}"
: "${DEVKIT_COMMAND_PROJECT_ROOT:="${DEVKIT_HOST_PROJECT_ROOT}"}"
: "${DEVKIT_HOST_HOME:="${HOME}"}"
: "${DEVKIT_COMMAND_HOME:="${DEVKIT_HOST_HOME}"}"
: "${DEVKIT_CONTAINER_HOME:="${DEVKIT_HOST_HOME}"}"
: "${TMPDIR:="/tmp"}" # do not export this
: "${DEVKIT_HOST_TMP_DIR:="${TMPDIR}"}"
: "${DEVKIT_CONTAINER_TMP_DIR:="${DEVKIT_HOST_TMP_DIR}"}"

readonly DEVKIT_HOST_PROJECT_ROOT
readonly DEVKIT_CONTAINER_PROJECT_ROOT
readonly DEVKIT_COMMAND_PROJECT_ROOT
readonly DEVKIT_HOST_HOME
readonly DEVKIT_COMMAND_HOME
readonly DEVKIT_CONTAINER_HOME
readonly DEVKIT_HOST_TMP_DIR
readonly DEVKIT_CONTAINER_TMP_DIR

# Array of files under ${DEVKIT_COMMAND_HOME} to be created (if don't exist) and mounted
declare -ar HOME_FILES=(
  ".gitconfig"
)

# Array of dirs under ${DEVKIT_COMMAND_HOME} to be created (if don't exist) and mounted
declare -ar HOME_DIRS=(
  ".cache/bazel"
  ".cache/bazelisk"
  ".cache/buf"
  ".cache/go-build"
  ".cache/nvim"
  ".cache/pip"
  ".cache/pip-tools"
  ".cache/pre-commit"
  ".cache/pylint"
  ".config/gcloud"
  ".config/google-chrome"
  ".config/matplotlib"
  ".devkit"
  ".docker"
  ".gemini"
  ".local/pre-commit"
  ".local/share/nvim"
  ".local/state"
  ".npm"
)

declare -r DOCKER_SOCKET="/var/run/docker.sock"
declare -r SYSTEM_BUS_SOCKET="/run/dbus/system_bus_socket"

declare -r DOCKER_GROUP="docker"
declare -i DOCKER_GROUP_ID
DOCKER_GROUP_ID=$(getent group "${DOCKER_GROUP}" | cut -d: -f3)

declare -r NOBODY_GROUP="nobody"
declare -i NOBODY_GROUP_ID
NOBODY_GROUP_ID=$(getent group "${NOBODY_GROUP}" | cut -d: -f3)

: "${USER:="$(id -u -n)"}"
: "${USER_ID:="$(id -u)"}"
: "${GROUP:="$(id -g -n)"}"
: "${GROUP_ID:="$(id -g)"}"

readonly USER_RUN_DIR="/run/user/${USER_ID}"
readonly SESSION_BUS_SOCKET="${USER_RUN_DIR}/bus"

declare -a MOUNTS=(
  "${DOCKER_SOCKET}"
  "${SYSTEM_BUS_SOCKET}"
  "${SESSION_BUS_SOCKET}"
)

for rel_path in "${HOME_DIRS[@]}"; do
  dir_path="${DEVKIT_COMMAND_HOME}/${rel_path}"
  mkdir -p "${dir_path}"
  MOUNTS+=("${dir_path}")
done

for rel_path in "${HOME_FILES[@]}"; do
  file_path="${DEVKIT_COMMAND_HOME}/${rel_path}"
  parent_dir="$(dirname "${file_path}")"
  mkdir -p "${parent_dir}"
  touch "${file_path}"
  MOUNTS+=("${file_path}")
done

declare -a ADDITIONAL_ENV=()
declare -a ADDITIONAL_PATHS=()

if git rev-parse --is-inside-work-tree &>/dev/null; then
  GIT_DIR="$(git rev-parse --absolute-git-dir)"
  readonly GIT_DIR
  if [[ "${GIT_DIR}" != "${PWD}"* ]]; then
    MOUNTS+=("${GIT_DIR}")
    ADDITIONAL_ENV+=("--env=GIT_DISCOVERY_ACROSS_FILESYSTEM=1")
  fi
fi

if [[ $NOBODY_GROUP_ID -gt 0 ]]; then
  ADDITIONAL_ENV+=("--env=NOBODY_GROUP_ID=${NOBODY_GROUP_ID}")
fi

declare -a LIST_EXTERNAL_MOUNTS_ARGS=()
LIST_EXTERNAL_MOUNTS_ARGS+=(--root-dir "${DEVKIT_COMMAND_PROJECT_ROOT}")
for path in "${MOUNTS[@]}"; do
  LIST_EXTERNAL_MOUNTS_ARGS+=(--mount "${path}")
done

mapfile -t MOUNTS < <("${SCRIPTS}/list_external_mounts.py" "${LIST_EXTERNAL_MOUNTS_ARGS[@]}")

declare -a DOCKER_RUN_ARGS=()
if [[ -t 0 ]] && [[ -t 1 ]]; then
  DOCKER_RUN_ARGS+=(
    "--interactive"
    "--tty"
  )
elif [[ ! -t 0 ]]; then
  DOCKER_RUN_ARGS+=("--interactive")
fi

mapfile -t DOCKER_RUN_ARGS_FROM_JSON < <(
  export DEVKIT_COMMAND_PROJECT_ROOT
  python3 - <<'EOF'
import json
import os
try:
    devkit_json_path = os.path.join(os.environ["DEVKIT_COMMAND_PROJECT_ROOT"], "devkit.json")
    with open(devkit_json_path) as f:
        data = json.load(f)
        args = data["docker"]["run"]
        if args:
            print("\n".join(args))
except Exception:
    pass
EOF
)

DOCKER_RUN_ARGS+=("${DOCKER_RUN_ARGS_FROM_JSON[@]}")

if [[ -n "${DEVKIT_DOCKER_RUN_ARGS:-}" ]]; then
  read -r -a devkit_docker_run_args <<<"${DEVKIT_DOCKER_RUN_ARGS}"
  DOCKER_RUN_ARGS+=("${devkit_docker_run_args[@]}")
fi

declare -a EVALUATED_DOCKER_RUN_ARGS=()
for arg in "${DOCKER_RUN_ARGS[@]}"; do
  eval "expanded_arg=${arg}"
  EVALUATED_DOCKER_RUN_ARGS+=("${expanded_arg}")
done

declare -a DOCKER_MOUNTS=()
for path in "${MOUNTS[@]}"; do
  host_path="${path}"
  container_path="${path}"
  if [[ "${path}" == "${DEVKIT_COMMAND_HOME}"* ]]; then
    path_suffix="${path#"${DEVKIT_COMMAND_HOME}"}"
    host_path="${DEVKIT_HOST_HOME}${path_suffix}"
    container_path="${DEVKIT_CONTAINER_HOME}${path_suffix}"
  fi
  DOCKER_MOUNTS+=("--volume=${host_path}:${container_path}")
done

function join_by_colon { local IFS=":"; echo "$*"; }
ADDITIONAL_PATH="$(join_by_colon "${ADDITIONAL_PATHS[@]}")"

docker run \
    --rm \
    --volume="${DEVKIT_HOST_PROJECT_ROOT}:${DEVKIT_CONTAINER_PROJECT_ROOT}" \
    --workdir="${PWD}" \
    --env="HOME=${DEVKIT_CONTAINER_HOME}" \
    --env="GOOGLE_CLOUD_PROJECT" \
    --env="GEMINI_API_KEY" \
    --env="GH_TOKEN" \
    --env="USER=${USER}" \
    --env="USER_ID=${USER_ID}" \
    --env="GROUP=${GROUP}" \
    --env="GROUP_ID=${GROUP_ID}" \
    --env="TMPDIR=${DEVKIT_CONTAINER_TMP_DIR}" \
    --env="DOCKER_GROUP=${DOCKER_GROUP}" \
    --env="DOCKER_GROUP_ID=${DOCKER_GROUP_ID}" \
    --env="NOBODY_GROUP=${NOBODY_GROUP}" \
    --env="DBUS_SYSTEM_BUS_ADDRESS=unix:path=${SYSTEM_BUS_SOCKET}" \
    --env="DBUS_SESSION_BUS_ADDRESS=unix:path=${SESSION_BUS_SOCKET}" \
    --env="ADDITIONAL_PATH=${ADDITIONAL_PATH}" \
    "${ADDITIONAL_ENV[@]}" \
    "${DOCKER_MOUNTS[@]}" \
    --net=host \
    --ipc=host \
    --hostname="$(hostname)" \
    --volume="${DEVKIT_HOST_TMP_DIR}:${DEVKIT_CONTAINER_TMP_DIR}" \
    --entrypoint="${SCRIPTS}/entrypoint_docker" \
    "${EVALUATED_DOCKER_RUN_ARGS[@]}" \
    "$@"
